module: MaterialMotionPopFamily
module_version: 1.1.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionPopFamily.xcworkspace
  - -scheme
  - MaterialMotionPopFamily
github_url: https://github.com/material-motion/material-motion-family-pop-swift
github_file_prefix: https://github.com/material-motion/material-motion-family-pop-swift/tree/v1.1.0
