module: MaterialMotionPop
module_version: 2.1.0
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MaterialMotionPop.xcworkspace
  - -scheme
  - MaterialMotionPop
github_url: https://github.com/material-motion/pop-swift
github_file_prefix: https://github.com/material-motion/pop-swift/tree/v2.1.0
